import {
  Users,
  Package,
  ShoppingCart,
  FileText,
  Settings,
  Home,
  Mail,
  Star,
  FolderOpen,
  List,
  Target,
  MessageSquare,
  Building,
  CreditCard,
  Calendar,
  Tag,
  Briefcase,
  Globe,
  Heart,
  Truck,
  Layers,
  BookOpen,
  Award,
  Clipboard,
  MapPin,
  Phone,
  Image,
  Zap,
  Shield,
  BarChart3,
  CircleDollarSign,
  FolderKanban,
  Flag,
  CheckSquare,
} from 'lucide-react';

const iconMap = {
  'users': Users,
  'package': Package,
  'shopping-cart': ShoppingCart,
  'file': FileText,
  'settings': Settings,
  'home': Home,
  'mail': Mail,
  'star': Star,
  'folder': FolderOpen,
  'list': List,
  'target': Target,
  'message-square': MessageSquare,
  'building': Building,
  'credit-card': CreditCard,
  'calendar': Calendar,
  'tag': Tag,
  'briefcase': Briefcase,
  'globe': Globe,
  'heart': Heart,
  'truck': Truck,
  'layers': Layers,
  'book-open': BookOpen,
  'award': Award,
  'clipboard': Clipboard,
  'map-pin': MapPin,
  'phone': Phone,
  'image': Image,
  'zap': Zap,
  'shield': Shield,
  'bar-chart': BarChart3,
  'dollar-sign': CircleDollarSign,
  'folder-kanban': FolderKanban,
  'flag': Flag,
  'check-square': CheckSquare,
};

export default iconMap;
